### ISSUE TITLE
redmine Internal 500 error

### ISSUE THREAD

**Issue by chenzhe07** [dergachev/redmine_git_remote#14]
hi, @dergachev , the error message  "redmine internal 500 error" occured when I add remote github repositories to my redmine,  the env of my server is: 

===
    system: CentOS release 6.4 (Final)
    plugin_path: $redmine_root/redmine_git_remote
    ruby: 1.8.7
    redmine: 2.6.3
    git: 1.7.1

The following is the operation steps:

1. Add git repositories:
![git0](https://cloud.githubusercontent.com/assets/1954680/7229459/73177460-e796-11e4-9637-23cb29a57c3a.png)

2. submit create:
![git2](https://cloud.githubusercontent.com/assets/1954680/7229295/ad871080-e794-11e4-912c-1d8779f1d397.png)

3. error message in $redmin_root/log/production.log

>    Started POST "/projects/manual/repositories" for 10.2.49.220 at Mon Apr 20 19:15:46 +0800 2015
>Processing by RepositoriesController#create as HTML  Parameters: {"repository"=>{"is_default"=>"0", "url"=>"/web/dbtools/", "identifier"=>"dbtools", "extra_clone_url"=>"https://github.com/chenzhe07/dbtools"}, "utf8"=>"✓", "authenticity_token"=>"A6vO7Qnx/CYFrgo8bfOYI2ntc0VfJz96Z3dpjRk14m0=", "commit"=>"创建", "project_id"=>"manual", "repository_scm"=>"GitRemote"}  Current user: chenzhe (id=5) Completed 500 Internal Server Error in 1179.1ms
>
>NoMethodError (undefined method `exists?' for Dir:Class):
>  app/controllers/repositories_controller.rb:55:in `create'

I have no idea for this error message, thanks a lot for your help.

**Comment by dergachev** [comment]
First, try not filling in the path to repository. It will auto-fill it with something like `$PATH_TO_REDMINE/plugins/redmine_git_remote/repos/github.com/chenzhen07/dbtools` and try to create that folder.  If that works, it's probably because your redmine user (often www-root, or redmine) doesn't have perms to create the folder `/web/dbtools`.

**Comment by chenzhe07** [comment]
500 Error is still there when I create the directory  `$PATH_TO_REDMINE/plugins/redmine_git_remote/repos/github.com/chenzhen07/dbtools` manually and  give the perms to the empty directory `repos/github.com/chenzhen07/dbtools`   and  `/web/dbtools` by  `chmod 777` .

Redmine user is apache.

**Can't see more help message when enable the debug log**:
>>Started POST "/projects/manual/repositories" for 10.2.49.220 at Tue Apr 21 09:51:57 +0800 2015
Processing by RepositoriesController#create as HTML  Parameters: {"utf8"=>"✓", "commit"=>"Create", "repository_scm"=>"GitRemote", "authenticity_token"=>"ZyLlgM4Ee2Akip+vblp6VnWPBWVL+BOlHpQR2RdL+dE=", "project_id"=>"manual", "repository"=>{"extra_clone_url"=>"https://github.com/chenzhe07/dbtools", "is_default"=>"0", "identifier"=>"dbtools-github", "url"=>""}} 
>>ESC[1mESC[36m (0.6ms)ESC[0m  ESC[1mSELECT MAX(`settings`.`updated_on`) AS max_id FROM `settings` ESC[0m 
>>ESC[1mESC[35mUser Load (0.6ms)ESC[0m  SELECT `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = ? LIMIT 1 [["id", 5]]
>>  Current user: chenzhe (id=5)
>>  ESC[1mESC[36mProject Load (0.5ms)ESC[0m  ESC[1mSELECT `projects`.* FROM `projects` WHERE `projects`.`identifier` = 'manual' LIMIT 1ESC[0m
>>  ESC[1mESC[35mSQL (0.4ms)ESC[0m  SELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = 13
>>  ESC[1mESC[36mSQL (0.2ms)ESC[0m  ESC[1mBEGINESC[0m
>>  ESC[1mESC[35m (0.2ms)ESC[0m  ROLLBACK
>>Completed 500 Internal Server Error in 1143.1ms
>>
>>NoMethodError (undefined method `exists?' for Dir:Class):
>>  app/controllers/repositories_controller.rb:55:in `create'

**Comment by dergachev** [comment]
Not sure, sorry! I don't have enough info to replicate this. 

In the meantime, can you figure out where exactly it's trying to clone the repo into if you don't provide a path? Does the apache user have permission to manually create the same?

**Comment by chenzhe07** [comment]
@dergachev , I think the reason is caused by ruby version, as the ruby 1.8.7  on my server,  and I noticed the item of the README.md file: 
>Tested on Redmine 2.6 and ruby 2.1

and the error message in the production.log:
>NoMethodError (undefined method `exists?' for Dir:Class):
>  app/controllers/repositories_controller.rb:55:in `create'

So, I use  `File.directory?(clone_path)` instead of  `Dir.exists`  in the `app/models/repository/git_remote.rb `;  the option `--mirror=fetch`  can also cause the error `Unable to run: git --git-dir #{clone_path} remote add #{clone_url}`

```
--- app/models/repository/git_remote_bak.rb	2015-04-22 10:58:22.407006391 +0800
+++ app/models/repository/git_remote.rb	2015-04-22 12:53:01.801337099 +0800
@@ -97,7 +97,8 @@
       return "#{clone_url} is not a valid remote."
     end
 
-    if Dir.exists? clone_path
+    
+    if File.directory?(clone_path)
       existing_repo_remote, status = RedmineGitRemote::PoorMansCapture3::capture2("git", "--git-dir", clone_path, "config", "--get", "remote.origin.url")
       return "Unable to run: git --git-dir #{clone_path} config --get remote.origin.url" unless status.success?
 
@@ -109,7 +110,7 @@
         return  "Unable to run: git init --bare #{clone_path}"
       end
 
-      unless system "git", "--git-dir", clone_path, "remote", "add", "--mirror=fetch", "origin",  clone_url
+      unless system "git", "--git-dir", clone_path, "remote", "add", "--mirror", "origin",  clone_url
         return  "Unable to run: git --git-dir #{clone_path} remote add #{clone_url}"
       end
     end
```
It works:

![s1](https://cloud.githubusercontent.com/assets/1954680/7267559/9f98494c-e8ef-11e4-8424-b8133bb10f08.png)


Thanks for your help.

**Comment by dergachev** [comment]
Cool, great job! 

I don't remember if I tested it on ruby 1.8 at any point. 
Does everything work now, including fetching updates? What version of redmine are you running?

**Comment by chenzhe07** [comment]
```
system: CentOS release 6.4 (Final)
plugin_path: $redmine_root/plugins/redmine_git_remote
ruby: 1.8.7
redmine: 2.6.3
git: 1.7.1
```
Yes, it seems everything is all right now, create new repository with `Path to repository` and `fetching updates manually` are in the normal work.
