### ISSUE TITLE
Invalid Git Command Format (on CentOS 6)

### ISSUE THREAD

**Issue by ferricoxide** [dergachev/redmine_git_remote#15]
Recently stood up RedMine on a CentOS 6.6 AWS instance. Installed your plugin. When I attempt to add a GitHub-hosted remote, I get an error message indicating:
~~~
Clone URL Unable to run: git --git-dir /RedMine/repositories/git/Test remote add git@github.com:<USERID>/<PROJECT>.git
~~~
Dropped to the command-line and manually ran what the plugin is attempting to run and got a usage error from Git. In order to get Git to do the proper operation, I had to change the invocation to:
~~~
Clone URL Unable to run: git --git-dir=/RedMine/repositories/git/Test remote add origin git@github.com:<USERID>/<PROJECT>.git
~~~
Host OS: CentOS 6.6 (updated yesterday - 2015-05-28)
Git Version: 1.7.1 (from the  git-1.7.1-3.el6_4.1.x86_64 found in the CentOS 6 standard repositories)

Should be noted that even though the command errors out, a prior operation *does* manage to create a skeleton directory at `/RedMine/repositories/git/Test`:
~~~
$ ls /RedMine/repositories/git/AMI6
branches  config  description  HEAD  hooks  info  objects  refs
~~~

**Comment by dergachev** [comment]
Hi @ferricoxide 
Thanks for trying redmine_git_remote! If you look at the code, you'll see it was just my error message that was missing "origin": https://github.com/dergachev/redmine_git_remote/blob/master/app/models/repository/git_remote.rb#L113

Here's the code with the mistaken error message:

```
      unless system "git", "--git-dir", clone_path, "remote", "add", "--mirror=fetch", "origin",  clone_url
        return  "Unable to run: git --git-dir #{clone_path} remote add #{clone_url}"
      end
```

I've just committed a fix to make the error message better.

I'm not sure, but in your case I suspect you have an older version of git that doesn't support the `--mirror=fetch` argument. Is it possible to upgrade to something like 1.8, or even 1.7.5?

**Comment by ferricoxide** [comment]
Unfortunately, the `git` that's included in EL6 (Red Hat/CentOS/SciLin) is quite out of date (1.7.1, I believe).

In general, I'm trying to stay within the distribution repos with RPM loads to make the transition of the framework out of dev to production a bit less fraught. Our IA folks generally make life more painful when you try to push software that doesn't come with a vendor update system.

At any rate, thanks for the update. I'll see what I can do about making a more recent version of `git` acceptable to our IA folks.

**Comment by dergachev** [comment]
I'll try and think whether the same thing can be achieved in the old version of git. :)

**Comment by nathan-pmt** [comment]
Ran into this problem With a CentOS 6.7 install. Ended up doing:

> git --version
> rpm -Uvh http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm
> yum update --assumeno
> yum install  perl-Git-1.9.0 git-1.9.0  yum-versionlock
> git --version
> yum versionlock git perl-Git

I should note that 1.9.0 version has a case-insensitivity vulnerability - so if you're repository and redmine machines aren't both on Linux* you should probably ignore the 1.9.0 & versionlock parts and upgrade to the latest version of git that Wandisco makes available.

* https://github.com/blog/1938-vulnerability-announced-update-your-git-clients
