### ISSUE TITLE
Add Repository fail

### ISSUE THREAD

**Issue by sungjunyoung** [dergachev/redmine_git_remote#28]
In Add Repository page, I filled out Clone URL with my ssh form ( git@bitbucket.org:XXX/XXX.git )
But error occured saying,

"Clone URL git@bitbucket.org:XXX/XXX.git is not a valid remote."

But Redmine log said Completed 200 OK.

What can I try to solve this problem?

**Comment by possebon** [comment]
I'm having the same issue but with Github.

**Comment by dergachev** [comment]
I usually debug these things by SSHing in as the user running redmine (this is important), going into the right directory, and then interactively running the command that apparently failed. Does that help?

**Comment by robertfausk** [comment]
I had the same issue. That's what worked for me:

1. You need On your server where redmine is installed create new ssh keys (you can use e.g. https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/).
2. In bitbucket admin https://bitbucket.org/XXX/XXX/admin/access-keys/ hit button "Add key" and copy your newly created public key. You should now be able to execute ```git clone git@bitbucket.org:XXX/XXX.git``` on your redmine server without problems.

Sadly I'm now getting an internal server error in redmine when I try to create a new repository.
Will investigate further and reply again.

**Comment by dergachev** [comment]
@robertfausk are you also having trouble with public repos? Also, don't forget to check redmine logs for errors.

**Comment by robertfausk** [comment]
This is the error I'm getting from redmine.log
```
Started POST "/projects/renttv/repositories" for 78.55.177.135 at 2017-03-13 16:30:18 +0100
Processing by RepositoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ceSJG7k65Q4LDMatDbJzle0P1HozN2LS8mieU+gUp9LORQzG3NQH1qpS6E8RWXExunsmKlf0o0zDQNYqIIMQVQ==", "repository_scm"=>"GitRemote", "repository"=>{"is_default"=>"1", "identifier"=>"", "url"=>"", "extra_clone_url"=>"git@bitbucket.org:robertfausk/myrepo.git"}, "commit"=>"Anlegen", "project_id"=>"myrepo"}
  Current user: robertfausk (id=1)
Completed 500 Internal Server Error in 122ms (ActiveRecord: 5.7ms)

RuntimeError (Unable to create directory /var/www/.ssh: Permission denied @ dir_s_mkdir - /var/www/.ssh):
  plugins/redmine_git_remote/app/models/repository/git_remote.rb:169:in `rescue in add_known_host'
  plugins/redmine_git_remote/app/models/repository/git_remote.rb:166:in `add_known_host'
  plugins/redmine_git_remote/app/models/repository/git_remote.rb:94:in `ensure_possibly_empty_clone_exists'
  plugins/redmine_git_remote/app/models/repository/git_remote.rb:84:in `initialize_clone'
  app/controllers/repositories_controller.rb:55:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by robertfausk** [comment]
> dergachev commented 14 days ago
> I usually debug these things by SSHing in as the user running redmine (this is important), going into the right directory, and then interactively running the command that apparently failed. Does that help?

**as the user running redmine (this is important)** That's the point. If my user running redmine is www-data then I run into problems.
@dergachev What about managing ssh keys for private repos via redmine frontend? Store them in a database table e.g.

**Comment by robertfausk** [comment]
I've created two new issues #30 and #31
